from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from reportlab.lib.enums import TA_CENTER
from PIL import Image as PILImage, ImageDraw
import tempfile, os
from datetime import datetime


class CaseReportGenerator:

    def generate(self, case, output_path):
        doc = SimpleDocTemplate(output_path, pagesize=A4,
            topMargin=2*cm, bottomMargin=2*cm, leftMargin=2*cm, rightMargin=2*cm)
        styles = getSampleStyleSheet()
        story = []

        title_style = ParagraphStyle('title', parent=styles['Title'],
            fontSize=18, spaceAfter=6, textColor=colors.HexColor('#1A2E4A'))
        story.append(Paragraph('CRIME SCENE INVESTIGATION REPORT', title_style))
        story.append(Paragraph('AI-Assisted Forensic Analysis', styles['Heading2']))
        story.append(Spacer(1, 0.5*cm))

        info_data = [
            ['Case Number:', case.case_number],
            ['Title:', case.title],
            ['Location:', case.location or 'Not specified'],
            ['Status:', case.status.upper()],
            ['Generated:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
        ]
        info_table = Table(info_data, colWidths=[4*cm, 12*cm])
        info_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#1A2E4A')),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('ROWBACKGROUNDS', (1, 0), (1, -1), [colors.HexColor('#EEF3FA'), colors.white]),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 1*cm))

        total_annotations = 0
        for evidence in case.evidence:
            if evidence.file_type not in ['jpg', 'jpeg', 'png']:
                continue
            if not evidence.annotations:
                continue

            story.append(Paragraph(f'Evidence: {evidence.original_filename}', styles['Heading3']))

            annotated_path = self._draw_annotations(evidence.file_path, evidence.annotations)
            if annotated_path:
                story.append(RLImage(annotated_path, width=16*cm, height=10*cm))
                story.append(Spacer(1, 0.3*cm))

            ann_data = [['#', 'Label', 'Source', 'Confidence']]
            for i, ann in enumerate(evidence.annotations, 1):
                conf = f'{ann.confidence*100:.1f}%' if ann.confidence else 'Manual'
                ann_data.append([str(i), ann.label, ann.source, conf])
                total_annotations += 1

            ann_table = Table(ann_data, colWidths=[1*cm, 6*cm, 4*cm, 4*cm])
            ann_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1A2E4A')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#F7F9FC'), colors.white]),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            story.append(ann_table)
            story.append(Spacer(1, 0.8*cm))

        story.append(Paragraph('Summary', styles['Heading2']))
        story.append(Paragraph(
            f'Total evidence items: {len(case.evidence)}. '
            f'Total annotated objects: {total_annotations}. '
            f'Report generated by AI Crime Scene Reconstruction System.',
            styles['Normal']
        ))

        doc.build(story)
        return output_path

    def _draw_annotations(self, image_path, annotations):
        try:
            img = PILImage.open(image_path).convert('RGB')
            draw = ImageDraw.Draw(img)
            w, h = img.size

            for ann in annotations:
                x = int(ann.x * w)
                y = int(ann.y * h)
                bw = int(ann.width * w)
                bh = int(ann.height * h)
                color = '#FF4136' if ann.source == 'auto' else '#2ECC40'
                draw.rectangle([x, y, x+bw, y+bh], outline=color, width=3)
                label = ann.label + (f' {ann.confidence*100:.0f}%' if ann.confidence else '')
                draw.text((x+2, y+2), label, fill=color)

            tmp = tempfile.NamedTemporaryFile(suffix='.jpg', delete=False)
            img.save(tmp.name, 'JPEG', quality=85)
            return tmp.name
        except Exception as e:
            print(f'Could not annotate image: {e}')
            return None
